### ISSUE TITLE
Error when installing Plotjuggler to ros2 dashing

### ISSUE THREAD

**Issue by mehmety888** [PlotJuggler/plotjuggler-ros-plugins#16]
I couldn't install plotjuggler plugin to ROS2 dashing.

When I execute following:
`sudo apt install ros-${ROS_DISTRO}-plotjuggler`
I got error E: Unable to locate package ros-dashing-plotjuggler

Then I tried to compile PlotJuggler from source.
I clone following repositories 
```
 mkdir -p ~/ws_plotjuggler/src
 cd ~/ws_plotjuggler/src
 git clone https://github.com/PlotJuggler/plotjuggler_msgs.git
 git clone https://github.com/facontidavide/PlotJuggler.git
 git clone https://github.com/PlotJuggler/plotjuggler-ros-plugins.git
```
When I execute rosdep install
```
cd ~/ws_plotjuggler
rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
```
I got the following error 
**ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
plotjuggler_msgs: Cannot locate rosdep definition for [message_runtime]**

**Comment by facontidavide** [comment]
Hi,

first of all, because of my limited time I decided to support only Foxy or newer (still need to fix Rolling and Galactic).

For the records **plotjuggler_msgs** should use the brancg **ros2**.

Unless a company/individual sponsor the effort (or someone contributes with a PR), I will not support Dashing nor Eloquent.
